dist: trusty

language: node_js
node_js:
  - "10"

addons:
  chrome: stable

cache:
  directories:
     - /node_modules

before_install:
  - cd demo/ionic-dev/greenpeace

install:
  - npm install

before_script:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

script:
  - npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
  - npm istanbul cover jasmine-node --captureExceptions spec/ 
  # - npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js

after_success:
    - cat /coverage/lcov.info | /node_modules/coveralls/bin/coveralls.js
    - rm -rf /coverage