dist: trusty
sudo: false

language: node_js
node_js:
  - "10"

addons:
  chrome: stable

cache:
  directories:
     - ./demo/ionic-dev/greenpeace/node_modules

before_install:
  - cd demo/ionic-dev/greenpeace

install:
  - npm install

before_script:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

script:
  - npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
  - ./demo/ionic-dev/greenpeace/node_modules/node_modules/.bin/istanbul cover jasmine-node --captureExceptions spec/ 
  # - npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js

after_success:
    - cat ./demo/ionic-dev/greenpeace/node_modules/coverage/lcov.info | ./demo/ionic-dev/greenpeace/node_modules/node_modules/coveralls/bin/coveralls.js
    - rm -rf ./demo/ionic-dev/greenpeace/node_modules/coverage